import type { Metadata } from "next";
import { DM_Sans } from "next/font/google";
import "./globals.css";
import ToasterContext from "@/context/ToasterContex";
import AuthContext from "@/context/AuthContext";
import NextTopLoader from 'nextjs-toploader'

const dmSans = DM_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={dmSans.className}>
      <NextTopLoader color="#6366F1" crawlSpeed={200}
            height={4}
            crawl={true}
            easing="ease" />
        <AuthContext>
          <ToasterContext />
          {children}
        </AuthContext>
      </body>
    </html>
  );
}
